package com.bridgelabz.SmartTravelAndTripManagementSystem.exception;

import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;

// Handles exceptions globally
@RestControllerAdvice
public class GlobalExceptionHandler {

    // Handles user not found exception, returns 404 NOT FOUND
    @ExceptionHandler(UserNotFoundException.class)
    public ResponseEntity<ErrorResponse> userNotFoundException(UserNotFoundException exception){

        ErrorResponse errorResponse = new ErrorResponse();

        errorResponse.setStatus(404);
        errorResponse.setMessage(exception.getMessage());
        errorResponse.setTimestamp(new Timestamp(System.currentTimeMillis()));

        return new ResponseEntity<ErrorResponse>(errorResponse, HttpStatus.NOT_FOUND);
    }

    // Handles validation errors generated by @Valid, Returns 400 BAD REQUEST
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ValidationErrorResponse> methodArgumentNotValidException(MethodArgumentNotValidException exception){

        // Stores field name and validation message
        Map<String, String> errors = new HashMap<>();

        // Gets all validation errors
        for(var error : exception.getBindingResult().getFieldErrors()){
            errors.put(error.getField(), error.getDefaultMessage());
        }

        ValidationErrorResponse validationErrorResponse = new ValidationErrorResponse();

        validationErrorResponse.setStatus(400);
        validationErrorResponse.setMessage("Validation failed");
        validationErrorResponse.setErrors(errors);

        return new ResponseEntity<>(validationErrorResponse, HttpStatus.BAD_REQUEST);
    }

    // Handles duplicate data and database constraint violations, returns 409 CONFLICT
    @ExceptionHandler(DataIntegrityViolationException.class)
    public ResponseEntity<ErrorResponse> dataIntegrityViolationException(DataIntegrityViolationException exception){

        ErrorResponse errorResponse = new ErrorResponse();

        errorResponse.setStatus(409);
        errorResponse.setMessage("Email already exists");
        errorResponse.setTimestamp(new Timestamp(System.currentTimeMillis()));

        return new ResponseEntity<ErrorResponse>(errorResponse, HttpStatus.CONFLICT);
    }

    // Handles unexpected exceptions, returns 500 INTERNAL SERVER ERROR
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponse> exception(Exception e){

        ErrorResponse errorResponse = new ErrorResponse();

        errorResponse.setStatus(500);
        errorResponse.setMessage("Internal server error");
        errorResponse.setTimestamp(new Timestamp(System.currentTimeMillis()));

        return new ResponseEntity<ErrorResponse>(errorResponse, HttpStatus.INTERNAL_SERVER_ERROR);
    }

}